name: Deploy to Laravel Forge

# Note: TypeScript checking is temporarily disabled due to vue-tsc v1.8.25 compatibility issues
# The build process still validates TypeScript through Vite

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging (Dev Branch)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for staging
        run: npm run build
        env:
          NODE_ENV: development

      - name: Deploy to Forge (Staging)
        run: |
          curl -X POST "${{ secrets.FORGE_STAGING_DEPLOY_URL }}" \
            --fail \
            --silent \
            --show-error \
            -H "Content-Type: application/json" \
            -d '{"branch": "dev"}'
        env:
          FORGE_STAGING_DEPLOY_URL: ${{ secrets.FORGE_STAGING_DEPLOY_URL }}

  deploy-production:
    name: Deploy to Production (Main Branch)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Forge (Production)
        run: |
          curl -X POST "${{ secrets.FORGE_PRODUCTION_DEPLOY_URL }}" \
            --fail \
            --silent \
            --show-error \
            -H "Content-Type: application/json" \
            -d '{"branch": "main"}'
        env:
          FORGE_PRODUCTION_DEPLOY_URL: ${{ secrets.FORGE_PRODUCTION_DEPLOY_URL }}
